workspace = { members = ["src/macros"] }
[package]
name = "zk_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ff = "0.13.0"
macros = {path="./src/macros"}
